In [1]:
from pymongo import MongoClient

In [2]:
x = open('mongo_access.csv', 'r').readline().split(",")
ip_address, port, sample_size = (x[0], int(x[1]), int(x[2]))

In [3]:
mongo_client = MongoClient(ip_address, port)
database_reference = mongo_client.twitter
collection_reference = database_reference.tweets

In [4]:
cursor = collection_reference.find()
print("Total Tweet Count in DB: {:,}".format(cursor.count()))

Total Tweet Count in DB: 2,126,094

In [5]:
cursor_sampl = collection_reference.aggregate([{'$sample': {'size': 5}}])
tweets_samples = list(cursor_sampl)
print("Number of Tweets: {:,}".format(len(tweets_samples)))

Number of Tweets: 5

In [6]:
tweets_samples[0]

{'_id': ObjectId('5a6a0c3436dd5f000166e3f0'),
 'contributors': None,
 'coordinates': None,
 'created_at': 'Thu Jan 25 16:56:19 +0000 2018',
 'display_text_range': [0, 140],
 'entities': {'hashtags': [{'indices': [19, 28], 'text': 'whiplash'},
   {'indices': [104, 109], 'text': 'care'}],
  'symbols': [],
  'urls': [{'display_url': 'twitter.com/i/web/status/9…',
    'expanded_url': 'https://twitter.com/i/web/status/956571447563972608',
    'indices': [116, 139],
    'url': 'https://t.co/FAmk0SIQCt'}],
  'user_mentions': []},
 'extended_tweet': {'display_text_range': [0, 238],
  'entities': {'hashtags': [{'indices': [19, 28], 'text': 'whiplash'},
    {'indices': [104, 109], 'text': 'care'},
    {'indices': [136, 148], 'text': 'caraccident'},
    {'indices': [160, 167], 'text': 'injury'}],
   'media': [{'display_url': 'pic.twitter.com/1zFXtRMsCD',
     'expanded_url': 'https://twitter.com/DoctorLiens/status/956571447563972608/photo/1',
     'id': 956571229678272512,
     'id_str': '956571229678272512',
     'indices': [239, 262],
     'media_url': 'http://pbs.twimg.com/media/DUZsdxtVAAA23ro.jpg',
     'media_url_https': 'https://pbs.twimg.com/media/DUZsdxtVAAA23ro.jpg',
     'sizes': {'large': {'h': 352, 'resize': 'fit', 'w': 547},
      'medium': {'h': 352, 'resize': 'fit', 'w': 547},
      'small': {'h': 352, 'resize': 'fit', 'w': 547},
      'thumb': {'h': 150, 'resize': 'crop', 'w': 150}},
     'type': 'photo',
     'url': 'https://t.co/1zFXtRMsCD'}],
   'symbols': [],
   'urls': [{'display_url': 'doctorsacceptliens.com/treatment-for-…',
     'expanded_url': 'https://www.doctorsacceptliens.com/treatment-for-whiplash-injury-chiropractic/',
     'indices': [215, 238],
     'url': 'https://t.co/qUi91bYVSA'}],
   'user_mentions': []},
  'extended_entities': {'media': [{'display_url': 'pic.twitter.com/1zFXtRMsCD',
     'expanded_url': 'https://twitter.com/DoctorLiens/status/956571447563972608/photo/1',
     'id': 956571229678272512,
     'id_str': '956571229678272512',
     'indices': [239, 262],
     'media_url': 'http://pbs.twimg.com/media/DUZsdxtVAAA23ro.jpg',
     'media_url_https': 'https://pbs.twimg.com/media/DUZsdxtVAAA23ro.jpg',
     'sizes': {'large': {'h': 352, 'resize': 'fit', 'w': 547},
      'medium': {'h': 352, 'resize': 'fit', 'w': 547},
      'small': {'h': 352, 'resize': 'fit', 'w': 547},
      'thumb': {'h': 150, 'resize': 'crop', 'w': 150}},
     'type': 'photo',
     'url': 'https://t.co/1zFXtRMsCD'}]},
  'full_text': 'Countless cases of #whiplash are seen every year in the US, with many of them not gaining the necessary #care that they deserve after a #caraccident. While the #injury may appear minor at onset... Check out more at https://t.co/qUi91bYVSA https://t.co/1zFXtRMsCD'},
 'favorite_count': 0,
 'favorited': False,
 'filter_level': 'low',
 'geo': None,
 'id': 956571447563972608,
 'id_str': '956571447563972608',
 'in_reply_to_screen_name': None,
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'is_quote_status': False,
 'lang': 'en',
 'place': {'attributes': {},
  'bounding_box': {'coordinates': [[[-124.482003, 32.528832],
     [-124.482003, 42.009519],
     [-114.131212, 42.009519],
     [-114.131212, 32.528832]]],
   'type': 'Polygon'},
  'country': 'United States',
  'country_code': 'US',
  'full_name': 'California, USA',
  'id': 'fbd6d2f5a4e4a15e',
  'name': 'California',
  'place_type': 'admin',
  'url': 'https://api.twitter.com/1.1/geo/id/fbd6d2f5a4e4a15e.json'},
 'possibly_sensitive': False,
 'quote_count': 0,
 'reply_count': 0,
 'retweet_count': 0,
 'retweeted': False,
 'source': '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
 'text': 'Countless cases of #whiplash are seen every year in the US, with many of them not gaining the necessary #care that… https://t.co/FAmk0SIQCt',
 'timestamp_ms': '1516899379994',
 'truncated': True,
 'user': {'contributors_enabled': False,
  'created_at': 'Wed Jul 13 03:29:34 +0000 2016',
  'default_profile': False,
  'default_profile_image': False,
  'description': 'Connecting attorneys with doctors working on a lien basis for accident victims',
  'favourites_count': 2881,
  'follow_request_sent': None,
  'followers_count': 360,
  'following': None,
  'friends_count': 1356,
  'geo_enabled': True,
  'id': 753068826674155520,
  'id_str': '753068826674155520',
  'is_translator': False,
  'lang': 'en',
  'listed_count': 3,
  'location': 'California, USA',
  'name': 'Doctors Accept Liens',
  'notifications': None,
  'profile_background_color': '000000',
  'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
  'profile_background_tile': False,
  'profile_banner_url': 'https://pbs.twimg.com/profile_banners/753068826674155520/1496612047',
  'profile_image_url': 'http://pbs.twimg.com/profile_images/864887837149155328/KSsBq4Uj_normal.jpg',
  'profile_image_url_https': 'https://pbs.twimg.com/profile_images/864887837149155328/KSsBq4Uj_normal.jpg',
  'profile_link_color': '1B95E0',
  'profile_sidebar_border_color': '000000',
  'profile_sidebar_fill_color': '000000',
  'profile_text_color': '000000',
  'profile_use_background_image': False,
  'protected': False,
  'screen_name': 'DoctorLiens',
  'statuses_count': 632,
  'time_zone': None,
  'translator_type': 'none',
  'url': 'http://www.doctorsacceptliens.com',
  'utc_offset': None,
  'verified': False},
 'user_processed': True}

In [7]:
import pandas as pd

In [8]:
twt_df = pd.DataFrame(tweets_samples)

In [9]:
twt_df.head()

,_id,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,...,quoted_status_id_str,reply_count,retweet_count,retweeted,source,text,timestamp_ms,truncated,user,user_processed
0,5a6a0c3436dd5f000166e3f0,None,None,Thu Jan 25 16:56:19 +0000 2018,"[0, 140]","{'hashtags': [{'text': 'whiplash', 'indices': ...",NaN,{'full_text': 'Countless cases of #whiplash ar...,0,False,...,NaN,0,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",Countless cases of #whiplash are seen every ye...,1516899379994,True,"{'id': 753068826674155520, 'id_str': '75306882...",True
1,5a65cbc136dd5f0001647205,None,None,Mon Jan 22 11:32:17 +0000 2018,"[12, 27]","{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0,False,...,NaN,0,0,False,"<a href=""http://twitter.com/download/android"" ...",@MAGA_Rocco Oh and the 14th,1516620737715,False,"{'id': 3253327682, 'id_str': '3253327682', 'na...",NaN
2,5a4f4711bfe2f900158834a9,None,None,Fri Jan 05 09:36:16 +0000 2018,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0,False,...,NaN,0,0,False,"<a href=""http://twitter.com"" rel=""nofollow"">Ge...",TEST_GEO_Hierarchy: 2f8ab30e-8122-4a89-8e92-32...,1515144976930,False,"{'id': 758415480881164288, 'id_str': '75841548...",NaN
3,5a4fb69747b2a100b5057d84,None,None,Fri Jan 05 17:32:07 +0000 2018,"[0, 33]","{'hashtags': [], 'urls': [], 'user_mentions': ...","{'media': [{'id': 949332692948037632, 'id_str'...",NaN,0,False,...,NaN,0,0,False,"<a href=""http://twitter.com/download/iphone"" r...",Se filtra foto mía en el gimnasio https://t.co...,1515173527237,False,"{'id': 801202, 'id_str': '801202', 'name': 'Ma...",NaN
4,5a79f38015ba4c00015721f5,None,None,Tue Feb 06 18:27:12 +0000 2018,"[0, 92]","{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,NaN,0,False,...,960920004827869185,0,0,False,"<a href=""http://twitter.com/download/iphone"" r...",But what made you even think that pose was coo...,1517941632278,False,"{'id': 282634387, 'id_str': '282634387', 'name...",NaN

In [10]:
twt_df.describe()

,favorite_count,id,in_reply_to_status_id,in_reply_to_user_id,quote_count,quoted_status_id,reply_count,retweet_count
count,5.0,5.000000e+00,1.000000e+00,1.000000e+00,5.0,1.000000e+00,5.0,5.0
mean,0.0,9.542926e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0
std,0.0,5.026343e+15,NaN,NaN,0.0,NaN,0.0,0.0
min,0.0,9.492129e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0
25%,0.0,9.493327e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0
50%,0.0,9.554027e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0
75%,0.0,9.565714e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0
max,0.0,9.609430e+17,9.552671e+17,8.085059e+17,0.0,9.609200e+17,0.0,0.0

In [11]:
twt_df.dtypes

_id                           object
contributors                  object
coordinates                   object
created_at                    object
display_text_range            object
entities                      object
extended_entities             object
extended_tweet                object
favorite_count                 int64
favorited                       bool
filter_level                  object
geo                           object
id                             int64
id_str                        object
in_reply_to_screen_name       object
in_reply_to_status_id        float64
in_reply_to_status_id_str     object
in_reply_to_user_id          float64
in_reply_to_user_id_str       object
is_quote_status                 bool
lang                          object
place                         object
possibly_sensitive            object
quote_count                    int64
quoted_status                 object
quoted_status_id             float64
quoted_status_id_str          object
reply_count                    int64
retweet_count                  int64
retweeted                       bool
source                        object
text                          object
timestamp_ms                  object
truncated                       bool
user                          object
user_processed                object
dtype: object

In [12]:
twt_df.get_dtype_counts()

bool        4
float64     3
int64       5
object     24
dtype: int64

In [13]:
# grab the user column which is JSON. Then convert it to a list... originally it's a Pandas.Series
twt_users = list(twt_df['user'])
# Create dataframe of the user info
twt_users_df = pd.DataFrame(twt_users)
twt_users_df.head()

,contributors_enabled,created_at,default_profile,default_profile_image,description,favourites_count,follow_request_sent,followers_count,following,friends_count,...,profile_text_color,profile_use_background_image,protected,screen_name,statuses_count,time_zone,translator_type,url,utc_offset,verified
0,False,Wed Jul 13 03:29:34 +0000 2016,False,False,Connecting attorneys with doctors working on a...,2881,None,360,None,1356,...,000000,False,False,DoctorLiens,632,None,none,http://www.doctorsacceptliens.com,NaN,False
1,False,Tue Jun 23 05:15:09 +0000 2015,True,False,None,7,None,14,None,42,...,333333,True,False,sushicraver1955,1506,None,none,None,NaN,False
2,False,Wed Jul 27 21:35:16 +0000 2016,True,False,None,0,None,24,None,0,...,333333,True,False,test5geo1798,500710,Pacific Time (US & Canada),none,None,-28800.0,False
3,False,Wed Feb 28 16:00:13 +0000 2007,False,False,Entrepreneur & Father^3 | Team member of @TEDx...,16264,None,17683,None,439,...,000000,False,False,Goldenmax,78062,Pacific Time (US & Canada),regular,http://goldenberg.soy,-28800.0,True
4,False,Fri Apr 15 15:57:00 +0000 2011,False,False,I Tell Jokes Standing Up 🎙| Seen On The BIG & ...,669,None,10474,None,270,...,666666,True,False,HtownWiley,17038,Central Time (US & Canada),none,None,-21600.0,False

In [14]:
twt_users_df.describe()

,favourites_count,followers_count,friends_count,id,listed_count,statuses_count,utc_offset
count,5.000000,5.000000,5.000000,5.000000e+00,5.000000,5.000000,3.000000
mean,3964.200000,5711.000000,421.400000,3.022969e+17,61.000000,119589.600000,-26400.000000
std,6976.586895,8053.662707,551.867557,4.139413e+17,112.749723,215400.080494,4156.921938
min,0.000000,14.000000,0.000000,8.012020e+05,1.000000,632.000000,-28800.000000
25%,7.000000,24.000000,42.000000,2.826344e+08,3.000000,1506.000000,-28800.000000
50%,669.000000,360.000000,270.000000,3.253328e+09,15.000000,17038.000000,-28800.000000
75%,2881.000000,10474.000000,439.000000,7.530688e+17,24.000000,78062.000000,-25200.000000
max,16264.000000,17683.000000,1356.000000,7.584155e+17,262.000000,500710.000000,-21600.000000